---
title: "Teaching"
---
<style>
body {
text-align: justify}
</style>
<!-- Teaching page under construction -->

I have had considerable teaching experience, having taught from the second year of my undergraduate program through to the end of my PhD. As a graduate student instructor (TA) at Berkeley, I received an Outstanding Graduate Student Instructor award, a Certificate of Teaching and Learning in Higher Education, and was invited to train new quantitative social science GSIs at a pre-semester, campus-wide teaching conference. As an undergraduate I served for three years as a Peer Assisted Study Session Facilitator (similar to TA) for introductory micro- and macroeconomics, during which time I received a ‘Most Valuable Facilitator’ award and helped develop a new anti-plagiarism module, the results of which I presented at a national conference. I will be pleased to provide a teaching portfolio, including a statement of teaching philosophy and student reviews, upon request.

&nbsp;

## Certificate
I received a [Certificate of Teaching and Learning in Higher Education](https://gsi.berkeley.edu/programs-services/certificate-program/) from UC Berkeley in 2017. The requirements of the certificate are:

 - Participation in the all-day Teaching Conference for First-Time GSIs at UC Berkeley
 - Successful completion of a 300-level course on pedagogy that has been approved for the Certificate Program in the relevant discipline
 - Successful completion of the GSI Professional Standards and Ethics Online Course
 - Participation in six qualifying Workshops on Teaching
 - At least two semesters of teaching as a GSI at UC Berkeley
 - GSI classroom teaching observation by, and consultation with, a faculty mentor
 - Development of a course syllabus that you have designed
 - Use of mid-semester teaching evaluations
 - Creation of a teaching portfolio (*available on request*)

&nbsp;

## Awards

 - Outstanding Graduate Student Instructor Award, UC Berkeley, Fall 2013.
 
 - Most Valuable Facilitator Award (Facilitator's Choice), Peer-Assisted Students Sessions (PASS) Program, Winter Semester, 2009.

&nbsp;

## Experience

 - Instructor, *Fundamentals of Microeconomics (ECG700)*, NC State, Fall 2020.

 - Instructor, Master of Development Practice Math Bootcamp, UC Berkeley, Summer 2014--2017 (4 summers).
 
 - Discipline-Cluster Workshop Leader for Quantitative Social Sciences, UC Berkeley GSI Teaching Conference, Spring 2017.
 
 - Teaching Assistant, *Dynamic Modeling* (ARE 298; a 2 week intensive course) for Prof. Christian Traeger, April 2015.
 
 - Graduate Student Instructor, *Mathematical Methods for Agricultural and Resource Economics* (ARE211) for Prof. Leo Simon, UC Berkeley, Fall 2014.
 
 - Graduate Student Instructor, *The Economics of Climate Change* (EEP 175) for Prof. Christian Traeger, UC Berkeley, Fall 2013.
 
 - ARE Departmental Tutor, *Mathematical Tools for Economists* (ECON 204), UC Berkeley, Summer 2013.
 
 - Teaching Assistant, *Introduction to Resource Economics* (RSEC1031) for Prof. Michael Harris, University of Sydney, Aug--Nov 2010.
 
 - Peer-Assisted Study Session Facilitator for *Introductory Micro- and Macroeconomics*, University of Sydney, 2008--2010 (6 semesters).
 
 - Video Peer Assisted Study Session Facilitator for an Anti-plagiarism Component of *Business in the Global Environment*, University of Sydney, 2009--2010 (2 semesters).



<!-- [Write up teaching paragraph--perhaps extract from Teaching Portfolio] -->
<!-- I won the Outstanding Graduate Student Instructor Award -->
<!-- earned and the Certificate of Teaching and Learning in Higher Education UC Berkeley. -->
